# .github/ISSUE_TEMPLATE/issue.yml
name: Issue
description: Bug report or feature request
title: "[<Type>] <short summary>"
labels: ["needs:triage"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature
        - Docs
        - Task
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the goal or problem
      placeholder: Write a short clear description
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: For bugs only
      placeholder: |
        1. Do this
        2. See that
        3. Observe result
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected result
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Example v1.2.3 on Windows 11
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues
